// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $$0 from "./islands/AddToCartButton/linx.tsx";
import * as $$1 from "./islands/AddToCartButton/shopify.tsx";
import * as $$2 from "./islands/AddToCartButton/vnda.tsx";
import * as $$3 from "./islands/AddToCartButton/vtex.tsx";
import * as $$4 from "./islands/AddToCartButton/wake.tsx";
import * as $$5 from "./islands/Alert.tsx";
import * as $$6 from "./islands/BannerCarousel/BannerCarousel.tsx";
import * as $$7 from "./islands/BtnPayment.tsx";
import * as $$8 from "./islands/ContainerNavItem.tsx";
import * as $$9 from "./islands/DepartmentCarousel/DepartmentCarousel.tsx";
import * as $$10 from "./islands/Header/Buttons.tsx";
import * as $$11 from "./islands/Header/Cart/linx.tsx";
import * as $$12 from "./islands/Header/Cart/shopify.tsx";
import * as $$13 from "./islands/Header/Cart/vnda.tsx";
import * as $$14 from "./islands/Header/Cart/vtex.tsx";
import * as $$15 from "./islands/Header/Cart/wake.tsx";
import * as $$16 from "./islands/Header/Drawers.tsx";
import * as $$17 from "./islands/Header/Header.tsx";
import * as $$18 from "./islands/Header/SearchInput.tsx";
import * as $$19 from "./islands/Header/Searchbar.tsx";
import * as $$20 from "./islands/Header/SearchbarDesktop.tsx";
import * as $$21 from "./islands/Header/ServiceButton.tsx";
import * as $$22 from "./islands/Newsletter.tsx";
import * as $$23 from "./islands/OutOfStock.tsx";
import * as $$24 from "./islands/Product/Shelf/Shelf.tsx";
import * as $$25 from "./islands/Product/ShelfWithTabs/ShelfWithTabs.tsx";
import * as $$26 from "./islands/ProductImageZoom.tsx";
import * as $$27 from "./islands/SearchControls.tsx";
import * as $$28 from "./islands/ShippingSimulation.tsx";
import * as $$29 from "./islands/SliderJS.tsx";
import * as $$30 from "./islands/Tabs/Context/Context.tsx";
import * as $$31 from "./islands/Tabs/Tab/Tab.tsx";
import * as $$32 from "./islands/Tabs/TabPanel/TabPanel.tsx";
import * as $$33 from "./islands/Tabs/Tabs.tsx";
import * as $$34 from "./islands/Tabs/TabsList/TabsList.tsx";
import * as $$35 from "./islands/TimerCampaign.tsx";
import * as $$36 from "./islands/WishlistButton.tsx";
import * as $$37 from "./islands/ui/Partners/Partners.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
  },
  islands: {
    "./islands/AddToCartButton/linx.tsx": $$0,
    "./islands/AddToCartButton/shopify.tsx": $$1,
    "./islands/AddToCartButton/vnda.tsx": $$2,
    "./islands/AddToCartButton/vtex.tsx": $$3,
    "./islands/AddToCartButton/wake.tsx": $$4,
    "./islands/Alert.tsx": $$5,
    "./islands/BannerCarousel/BannerCarousel.tsx": $$6,
    "./islands/BtnPayment.tsx": $$7,
    "./islands/ContainerNavItem.tsx": $$8,
    "./islands/DepartmentCarousel/DepartmentCarousel.tsx": $$9,
    "./islands/Header/Buttons.tsx": $$10,
    "./islands/Header/Cart/linx.tsx": $$11,
    "./islands/Header/Cart/shopify.tsx": $$12,
    "./islands/Header/Cart/vnda.tsx": $$13,
    "./islands/Header/Cart/vtex.tsx": $$14,
    "./islands/Header/Cart/wake.tsx": $$15,
    "./islands/Header/Drawers.tsx": $$16,
    "./islands/Header/Header.tsx": $$17,
    "./islands/Header/SearchInput.tsx": $$18,
    "./islands/Header/Searchbar.tsx": $$19,
    "./islands/Header/SearchbarDesktop.tsx": $$20,
    "./islands/Header/ServiceButton.tsx": $$21,
    "./islands/Newsletter.tsx": $$22,
    "./islands/OutOfStock.tsx": $$23,
    "./islands/Product/Shelf/Shelf.tsx": $$24,
    "./islands/Product/ShelfWithTabs/ShelfWithTabs.tsx": $$25,
    "./islands/ProductImageZoom.tsx": $$26,
    "./islands/SearchControls.tsx": $$27,
    "./islands/ShippingSimulation.tsx": $$28,
    "./islands/SliderJS.tsx": $$29,
    "./islands/Tabs/Context/Context.tsx": $$30,
    "./islands/Tabs/Tab/Tab.tsx": $$31,
    "./islands/Tabs/TabPanel/TabPanel.tsx": $$32,
    "./islands/Tabs/Tabs.tsx": $$33,
    "./islands/Tabs/TabsList/TabsList.tsx": $$34,
    "./islands/TimerCampaign.tsx": $$35,
    "./islands/WishlistButton.tsx": $$36,
    "./islands/ui/Partners/Partners.tsx": $$37,
  },
  baseUrl: import.meta.url,
};

export default manifest;
