// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/Layouts/ProductCard.tsx";
import * as $$$1 from "./loaders/List/Sections.tsx";
import * as $$$2 from "./loaders/simulate.ts";
import * as $$$3 from "./loaders/getPaymentMethods.ts";
import * as $$$$$$0 from "./sections/Content/Faq.tsx";
import * as $$$$$$1 from "./sections/Content/Benefits.tsx";
import * as $$$$$$2 from "./sections/Content/Logos.tsx";
import * as $$$$$$3 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$4 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$5 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$6 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$7 from "./sections/Images/Banner.tsx";
import * as $$$$$$8 from "./sections/Images/BannerGrid.tsx";
import * as $$$$$$9 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$10 from "./sections/Images/Carousel.tsx";
import * as $$$$$$11 from "./sections/BannerCarousel/BannerCarousel.tsx";
import * as $$$$$$12 from "./sections/Institutional/Institutional.tsx";
import * as $$$$$$13 from "./sections/Theme/Theme.tsx";
import * as $$$$$$14 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$15 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$16 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$17 from "./sections/Product/ProductInfo.tsx";
import * as $$$$$$18 from "./sections/Product/Page/Page.tsx";
import * as $$$$$$19 from "./sections/Product/ShelfCampaign.tsx";
import * as $$$$$$20 from "./sections/Product/Cupom/Cupom.tsx";
import * as $$$$$$21 from "./sections/Product/NotFound.tsx";
import * as $$$$$$22 from "./sections/Product/Shelf/Shelf.tsx";
import * as $$$$$$23 from "./sections/Product/ShelfWithTabs/ShelfWithTabs.tsx";
import * as $$$$$$24 from "./sections/Product/NotFoundChallenge.tsx";
import * as $$$$$$25 from "./sections/Layout/GridItem.tsx";
import * as $$$$$$26 from "./sections/Layout/Grid.tsx";
import * as $$$$$$27 from "./sections/Layout/Flex.tsx";
import * as $$$$$$28 from "./sections/Layout/Container.tsx";
import * as $$$$$$29 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$30 from "./sections/Footer/Footer.tsx";
import * as $$$$$$31 from "./sections/Gallery.tsx";
import * as $$$$$$32 from "./sections/DepartmentCarousel/DepartmentCarousel.tsx";
import * as $$$$$$33 from "./sections/Header/Header.tsx";
import * as $$$$$$34 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$35 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$36 from "./sections/Seals/Seals.tsx";
import * as $$$$$$37 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$38 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$39 from "./sections/GridBanners/GridBanners.tsx";
import * as $$$$$$40 from "./sections/Category/CategoryList.tsx";
import * as $$$$$$41 from "./sections/Category/Partners.tsx";
import * as $$$$$$42 from "./sections/Category/DepartmentList.tsx";
import * as $$$$$$43 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";

const manifest = {
  "loaders": {
    "deco-sites/storefront/loaders/getPaymentMethods.ts": $$$3,
    "deco-sites/storefront/loaders/Layouts/ProductCard.tsx": $$$0,
    "deco-sites/storefront/loaders/List/Sections.tsx": $$$1,
    "deco-sites/storefront/loaders/simulate.ts": $$$2,
  },
  "sections": {
    "deco-sites/storefront/sections/BannerCarousel/BannerCarousel.tsx":
      $$$$$$11,
    "deco-sites/storefront/sections/Category/CategoryBanner.tsx": $$$$$$43,
    "deco-sites/storefront/sections/Category/CategoryList.tsx": $$$$$$40,
    "deco-sites/storefront/sections/Category/DepartmentList.tsx": $$$$$$42,
    "deco-sites/storefront/sections/Category/Partners.tsx": $$$$$$41,
    "deco-sites/storefront/sections/Content/Benefits.tsx": $$$$$$1,
    "deco-sites/storefront/sections/Content/Faq.tsx": $$$$$$0,
    "deco-sites/storefront/sections/Content/Logos.tsx": $$$$$$2,
    "deco-sites/storefront/sections/Content/Testimonials.tsx": $$$$$$3,
    "deco-sites/storefront/sections/DepartmentCarousel/DepartmentCarousel.tsx":
      $$$$$$32,
    "deco-sites/storefront/sections/Footer/Footer.tsx": $$$$$$30,
    "deco-sites/storefront/sections/Gallery.tsx": $$$$$$31,
    "deco-sites/storefront/sections/GridBanners/GridBanners.tsx": $$$$$$39,
    "deco-sites/storefront/sections/Header/Header.tsx": $$$$$$33,
    "deco-sites/storefront/sections/Images/Banner.tsx": $$$$$$7,
    "deco-sites/storefront/sections/Images/BannerGrid.tsx": $$$$$$8,
    "deco-sites/storefront/sections/Images/Carousel.tsx": $$$$$$10,
    "deco-sites/storefront/sections/Images/ImageGallery.tsx": $$$$$$6,
    "deco-sites/storefront/sections/Images/ShoppableBanner.tsx": $$$$$$9,
    "deco-sites/storefront/sections/Institutional/Institutional.tsx": $$$$$$12,
    "deco-sites/storefront/sections/Layout/Container.tsx": $$$$$$28,
    "deco-sites/storefront/sections/Layout/Flex.tsx": $$$$$$27,
    "deco-sites/storefront/sections/Layout/Grid.tsx": $$$$$$26,
    "deco-sites/storefront/sections/Layout/GridItem.tsx": $$$$$$25,
    "deco-sites/storefront/sections/Links/LinkTree.tsx": $$$$$$5,
    "deco-sites/storefront/sections/Links/Shortcuts.tsx": $$$$$$4,
    "deco-sites/storefront/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$34,
    "deco-sites/storefront/sections/Miscellaneous/CookieConsent.tsx": $$$$$$35,
    "deco-sites/storefront/sections/Newsletter/Newsletter.tsx": $$$$$$29,
    "deco-sites/storefront/sections/Product/Cupom/Cupom.tsx": $$$$$$20,
    "deco-sites/storefront/sections/Product/NotFound.tsx": $$$$$$21,
    "deco-sites/storefront/sections/Product/NotFoundChallenge.tsx": $$$$$$24,
    "deco-sites/storefront/sections/Product/Page/Page.tsx": $$$$$$18,
    "deco-sites/storefront/sections/Product/ProductInfo.tsx": $$$$$$17,
    "deco-sites/storefront/sections/Product/ProductShelf.tsx": $$$$$$16,
    "deco-sites/storefront/sections/Product/SearchResult.tsx": $$$$$$15,
    "deco-sites/storefront/sections/Product/Shelf/Shelf.tsx": $$$$$$22,
    "deco-sites/storefront/sections/Product/ShelfCampaign.tsx": $$$$$$19,
    "deco-sites/storefront/sections/Product/ShelfWithTabs/ShelfWithTabs.tsx":
      $$$$$$23,
    "deco-sites/storefront/sections/Product/Wishlist.tsx": $$$$$$14,
    "deco-sites/storefront/sections/Seals/Seals.tsx": $$$$$$36,
    "deco-sites/storefront/sections/Social/InstagramPosts.tsx": $$$$$$38,
    "deco-sites/storefront/sections/Social/WhatsApp.tsx": $$$$$$37,
    "deco-sites/storefront/sections/Theme/Theme.tsx": $$$$$$13,
  },
  "apps": {
    "deco-sites/storefront/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/storefront/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/storefront",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
